# Generated by Django 3.0.7 on 2020-06-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_timer',
            field=models.IntegerField(default=0),
        ),
    ]
