# Generated by Django 3.0.7 on 2020-06-25 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_start_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
