# Generated by Django 3.0.7 on 2020-07-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_move_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_time',
            field=models.BooleanField(default=True),
        ),
    ]
