# Generated by Django 3.0.7 on 2020-07-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_has_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_remaining_black',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_remaining_white',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='move',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
