# Generated by Django 3.0.7 on 2020-06-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='confirmed_email',
            field=models.BooleanField(default=False),
        ),
    ]
