# Generated by Django 3.0.7 on 2020-06-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
